=== summanlp/summa-visualization/evaluation/datasets/cmplg/sources/mini.dtd
<?xml encoding="US-ASCII"?>

<!-- mini, DTD v 1.0, 19970701                                     -->

<!--======================================================================-->

<!ELEMENT MINIMAL-DOC (FILENO?,TITLE,AUTHORS?,APPEARED?,ABSTRACT,BODY)>

<!ELEMENT FILENO (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT AUTHORS (AUTHOR)*>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT APPEARED (#PCDATA)>
<!ELEMENT ABSTRACT (#PCDATA|ITEMIZE|CREF|REF|EQN|FOOTNOTE|IMAGE|P)*>
<!ELEMENT BODY (DIV|P|ITEMIZE)*>
<!ELEMENT CLASSIFICATION (#PCDATA)>

<!ELEMENT P (#PCDATA|ITEMIZE|CREF|REF|EQN|FOOTNOTE|IMAGE)*>

<!ELEMENT DIV (HEADER, (DIV|P|ITEMIZE|IMAGE)*)>
<!ATTLIST DIV   
          ID     CDATA  #REQUIRED
          DEPTH  CDATA  #REQUIRED
          R-NO   CDATA  #REQUIRED>

<!ELEMENT HEADER (#PCDATA|EQN)*>

<!ELEMENT IMAGE EMPTY>
          <!-- TYPE (FIGURE|TABLE) #REQUIRED -->
<!ATTLIST IMAGE 
          TYPE   CDATA  #REQUIRED>

<!ELEMENT ITEMIZE (#PCDATA|ITEM)*>

<!ELEMENT ITEM (#PCDATA|ITEMIZE|CREF|REF|EQN|FOOTNOTE|IMAGE)*>

<!ELEMENT CREF EMPTY>
<!ELEMENT REF EMPTY>
<!ELEMENT EQN EMPTY>
<!ELEMENT FOOTNOTE EMPTY>

=== summanlp/summa-visualization/evaluation/datasets/cmplg/9605002.xml
<?xml version='1.0'?>
<!DOCTYPE MINIMAL-DOC SYSTEM "mini.dtd">
<MINIMAL-DOC>
<TITLE>Building Natural Language Generation Systems</TITLE>
<ABSTRACT>
<P>
Natural Language Generation (NLG) systems generate texts in English
(or other human
languages, such as French) from computer-accessible data.  NLG systems are
(currently) most often used to help human authors write routine documents,
 including business letters <REF/> and  weather reports <REF/>.  They also have been used as interactive explanation tools which communicate information in
an understandable way to non-expert users, especially in software
 engineering (eg, <REF/>) and medical (eg, <REF/>) contexts.
From a technical perspective, almost all applied NLG systems perform the
 following three tasks <REF/>: 
Content Determination and Text Planning:
Decide what information should be communicated to the user (content
determination), and how this information should be rhetorically structured
(text planning).  These tasks are usually done simultaneously.
Sentence Planning:
Decide how the information will be split among individual sentences and
paragraphs, and what cohesion devices
(eg, pronouns, discourse markers)
should be added to make the text flow smoothly.
Realization:
Generate the individual sentences in a grammatically correct manner.
In the rest of this paper, I shall briefly discuss different ways of
performing each of these tasks.
</P>
</ABSTRACT>
<BODY>
<DIV ID="1" DEPTH="1" R-NO="1"><HEADER>  Content Determination and Text Planning </HEADER>
<P>
Content determination (deciding what information to communicate in the text)
and text-planning (organizing the information into a rhetorically coherent
structure) are done simultaneously in most applied NLG systems
 <REF/>.  These tasks can be done at many different levels of sophistication.  One of the simplest (and most common) approaches is simply
to write a `hard-coded' content/text-planner in a standard programming language
(C++, Lisp, etc).  The resultant system may lack
flexibility, but if the texts being produced have a standardized
content and structure (which is true in many technical
domains), then this can be the most effective way to perform these tasks.
</P>
<P>
On the other end of the sophistication spectrum, many standard AI techniques
have been adopted for content determination and text planning,
 including rule-based systems <REF/> and planning <REF/>. Systems built in this way are in principal very flexible and powerful,
although in practice they have sometimes not been
robust enough for real-world use.
</P>
<P>
An intermediate approach which has been quite popular is to use a
 special `schema' or `text-planning' language <REF/>,<REF/>. Such languages typically allow the developer to represent text plans as
transition networks of one sort or another, with the nodes giving the
information content and the arcs giving the rhetorical structure
In many cases text-planning languages are implemented as macro packages,
which gives the developer access to the full power of the underlying
programming language whenever necessary.
</P>
</DIV>
<DIV ID="2" DEPTH="1" R-NO="2"><HEADER>  Sentence Planning </HEADER>
<P>
Sentence planning includes
<ITEMIZE>
<ITEM>Conjunction and other aggregation.  For example, transforming (1)
into (2):
1)
Sam has high blood pressure.  Sam has low blood sugar.
2)
Sam has high blood pressure and low blood sugar.
</ITEM>
<ITEM>Pronominalization and other reference.  For example, transforming
(3) into (4):
3)
I just saw Mrs. Black.  Mrs Black has a high temperature.
4)
I just saw Mrs. Black.  She has a high temperature.
</ITEM>
<ITEM>Introducing discourse markers.  For example, transforming (5) into (6):
5)
If Sam goes to the hospital, he should go to the store.
6)
If Sam goes to the hospital, he should also go to the store.
</ITEM>
</ITEMIZE>
The common theme behind these operations is they do not change the
information content of the text, but they do make it more fluent and easily
readable.
</P>
<P>
Sentence planning is important if the text needs to read fluently and,
in particular, if it should look like it was written by a human (which is
usually the case for business letters, for example).  If it doesn't matter
if the text sounds stilted and was obviously produced by a computer, then
it may be possible to de-emphasize sentence planning, and perform minimal
aggregation, use no pronouns, etc.
</P>
<P>
If the text does need to look fluent, then a good job of sentence planning
is essential.  There are formal models of all of the operations mentioned
above, and some applied NLG systems have incorporated them, eg,
 <REF/>.  It is also possible to do effective sentence-planning in an ad-hoc manner, at least in a limited domain;
Knowledge Point's Performance Now system is a good example of this.
</P>
</DIV>
<DIV ID="3" DEPTH="1" R-NO="3"><HEADER>  Realization </HEADER>
<P>
A Realizer generates individual sentences (typically from a
 `deep syntactic' representation <REF/>).  The realizer needs to make sure that the rules of English are obeyed, including
<ITEMIZE>
<ITEM>Point absorption and other punctuation rules.  For example, the sentence
I saw Helen Jones, my sister-in-law should end in ``.'', not ``,.''
</ITEM>
<ITEM>Morphology.  For example, the plural of box is
boxes, not boxs.
</ITEM>
<ITEM>Agreement.  For example, I am here instead of
I is here.
</ITEM>
<ITEM>Reflexives.  For example, John saw himself, instead of
John saw John.
</ITEM>
</ITEMIZE>
</P>
<P>
There are numerous linguistic formalisms and theories which can be
incorporated into an NLG Realizer, far too many to describe here.
There are also some general-purpose `engines' which can be programmed
 with various linguistic rules, such as FUF <REF/>  and PENMAN <REF/>. 
</P>
<P>
In many cases, acceptable performance can be achieved without
using complex linguistic modules.  In particular, if only a few different
types of sentences are being generated, then it may be simpler and cheaper
to use fill-in-the-blank templates for realization, instead of
`proper' syntactic processing.
</P>
</DIV>
<DIV ID="4" DEPTH="1" R-NO="4"><HEADER>  Conclusion </HEADER>
<P>
Many different techniques are available for performing the three NLG tasks
of content determination (and text planning),
sentence planning, and realization.
These techniques range from the simplistic to the extremely
sophisticated, and it is impossible to say that one is always `better' than
another.  It all depends on the characteristics of the application, such as
whether extensive filtering and summarization of information is needed,
whether texts need to `look like they were written by a person', and
how much syntactic variety is expected to occur in the generated texts.
A good NLG engineer will choose the most appropriate set of
 techniques, given the needs of the application <REF/> and the available resources.
</P>
<DIV ID="4.1" DEPTH="2" R-NO="1"><HEADER>Bibliography </HEADER>
<P>
B. Buchanan, J. Moore, D. Forsythe, G. Carenini, and S. Ohlsson.
Using medical informatics for explanation in a clinical setting.
Technical Report 93-16, Intelligent Systems Laboratory, University of
  Pittsburgh, 1994.
</P>
<P>
Michael Elhadad.
Using Argumentation to Control Lexical Choice: A Functional
  Unification Implementation.
PhD thesis, Columbia University, 1992.
</P>
<P>
Eli Goldberg, Norbert Driedger, and Richard Kittredge.
Using natural-language processing to produce weather forecasts.
IEEE Expert, 9(2):45-53, 1994.
</P>
<P>
Eduard Hovy.
Planning coherent multisentential text.
In Proceedings of 26th Annual Meeting of the Association for
  Computational Linguistics (ACL-88), pages 163-169, 1988.
</P>
<P>
Richard Kittredge, Tanya Korelsky, and Owen Rambow.
On the need for domain communication language.
Computational Intelligence, 7(4):305-314, 1991.
</P>
<P>
Kathleen McKeown.
Text Generation.
Cambridge University Press, 1985.
</P>
<P>
Kathleen McKeown, Karen Kukich, and James Shaw.
Practical issues in automatic document generation.
In Proceedings of the Fourth Conference on Applied
  Natural-Language Processing (ANLP-1994), pages 7-14, 1994.
</P>
<P>
Penman Natural Language Group.
The Penman user guide.
Technical report, Information Sciences Institute, Marina del Rey, CA
  90292, 1989.
</P>
<P>
Owen Rambow and Tanya Korelsky.
Applied text generation.
In Proceedings of the Third Conference on Applied Natural
  Language Processing (ANLP-1992), pages 40-47, 1992.
</P>
<P>
Ehud Reiter.
Has a consensus NL Generation architecture appeared, and is it
  psycholinguistically plausible?
In Proceedings of the Seventh International Workshop on Natural
  Language Generation (INLGW-1994), pages 163-170, 1994.
</P>
<P>
Ehud Reiter and Chris Mellish.
Optimising the costs and benefits of natural language generation.
In Proceedings of the 13th International Joint Conference on
  Artificial Intelligence (IJCAI-1993), volume 2, pages 1164-1169, 1993.
</P>
<P>
Ehud Reiter, Chris Mellish, and John Levine.
Automatic generation of technical documentation.
Applied Artificial Intelligence, 9(3):259-287, 1995.
</P>
<P>
Stephen Springer, Paul Buta, and Thomas Wolf.
Automatic letter composition for customer service.
In Reid Smith and Carlisle Scott, editors, Innovative
  Applications of Artificial Intelligence 3 (Proceedings of CAIA-1991). AAAI
  Press, 1991.
</P>
<P>
</P>
</DIV>
</DIV>
</BODY>
</MINIMAL-DOC>

=== summanlp/summa-visualization/evaluation/datasets/cmplg/sources/9502031.xml
<?xml version='1.0'?>
<!DOCTYPE MINIMAL-DOC SYSTEM "mini.dtd">
<MINIMAL-DOC>
<TITLE>Cooperative Error Handling and Shallow Processing</TITLE>
<ABSTRACT>
<P>
This
  paper is concerned with the detection and correction of
  sub-sentential English text errors.  Previous spelling programs,
  unless restricted to a very small set of words, have operated as
  post-processors.  And to date, grammar checkers and other programs
  which deal with ill-formed input usually step directly from spelling
  considerations to a full-scale parse, assuming a complete sentence.
  Work described below is aimed at evaluating the effectiveness of
  shallow (sub-sentential) processing and the feasibility of
  cooperative error checking, through building and testing
  appropriately an error-processing system.  A system under
  construction is outlined which incorporates morphological checks
  (using new two-level error rules) over a directed letter graph, tag
  positional trigrams and partial parsing.  Intended testing is
  discussed.
</P>
</ABSTRACT>
<BODY>
<DIV ID="1" DEPTH="1" R-NO="1"><HEADER>  Introduction </HEADER>
<P>
Unless a keyboard user is particularly proficient, a frustrating
amount of time is usually spent backtracking to pick up mis-typed or
otherwise mistaken input.  Work described in this paper started from
an idea of an error processor that would sit on top of an editor,
detecting/correcting errors just after entry, while the user continued
with further text, relieved from tedious backtracking.  Hence
`co-operative' error processing.  But if a program is to catch such
errors very soon after they are entered, it will have to operate with
less than the complete sentence.
</P>
<P>
Work underway focuses on shallow processing: how far error detection
and correction can proceed when the system purview is set to a stretch
of text which does not admit complete sentential analysis.  To date,
grammar checkers and other programs which deal with illformed input
usually step directly from spelling considerations to a full-scale
sentence parse.  However treating the sentence as a basic unit loses
meaning when the `sentence' is incomplete or illformed.  Shallow
processing is also interesting because it should be cheaper and faster
than a complete analysis of the whole sentence.
</P>
<P>
To investigate issues involved in shallow processing and cooperative
error handling, the pet (processing errors in text) system is
being built.  The focus is on these two issues; no attempt is being
 made to produce a complete product .  Pet operates over a shifting window of text (it can be attached simply and asynchronously to the Emacs
editor).  One word in this purview is in focus at a time.  Pet
will give one of three responses to this word; it will accept the
word, suggest a correction, or indicate that it found an error it
couldn't correct.  Below follow an outline and discussion of the
(linguistic) components of pet and discussion of testing and
evaluation of the system.
</P>
</DIV>
<DIV ID="2" DEPTH="1" R-NO="2"><HEADER>  Pet System </HEADER>
<P>
Morphological Processing  Spelling Checking
</P>
<P>
The word in focus is first passed through a two-level morphological analysis
stage,
based on an adaption of (Pulman, 1991).  Two purposes are served here: checking
the word is lexical (i.e. in the lexicon or a permissible inflection of
a word in the lexicon) and collecting the possible categories, which
are represented as sets of feature specifications (Grover, 1993).
</P>
<P>
This morphological lookup operates over a character trie which
has been compressed into a (directed) graph. Common endings are shared
and category information is stored on the first unique transition.  The
advantages of this compression are that (1) a word/morpheme is
recognised (and category affixation rules (Grover, 1993) checked) as soon as
the initial
letters allow uniqueness, rather than at the end of the word, and (2) there
is an immense saving of space. There was a reduction of over half the
transitions on
the trie formed from the Alvey lexicon.
</P>
<P>
If the word is unknown, the system reconsiders analysis from the point
where it broke down with the added possibility of an error rule.
There are currently four error rules, corresponding to the four Damerau
transformations: omission, insertion, transposition, substitution (Damerau,
1964) -
considered in that order (Pollock, 1983).
The error rules are in two level format and integrate seamlessly into
morphological
analysis.
</P>
<P>
 * - X - * 
<!-- MATH: $\rightarrow$ -->
<EQN/>
* - - *
</P>
</DIV>
<DIV ID="3" DEPTH="1" R-NO="3"><HEADER>  Testing and Evaluation </HEADER>
<P>
With the aim of evaluating the effectiveness of shallow processing,
tests will be carried out
to see what proportion of different types of errors can be dealt with
elegantly, adequately and/or efficiently.  Under examination will be
the number of errors missed/caught and wrongly/rightly corrected.
Different components and
configurations of the system will be compared, for example the
error rules v. p.b.t.'s.  Parameters of the
system will be varied, for example the breadth of the purview, the
position of the purview focus, the number of correction candidates and
the timing of their generation.  Will shallow processing miss too
many of the errors cooperative error processing is aimed at?
</P>
<P>
There are two significant difficulties with collecting test data.
The central difficulty is finding a representative sample of
genuine errors by native speakers, in context, with the correct version of
the text attached. Apart from anything else, `representative' is
hard to decide - spectrum of errors or distribution of errors ?
Secondly, any corpus of text usually contains only those errors that were
left undetected in the text.  Cooperative processing deals with errors that one
backtracks to catch; if not a different class or range, these at least might
have
a different distribution of error types.
</P>
<P>
The ideal data would be records of peoples' keystrokes when interacting with
an editor while creating or editing a piece of text.  This would allow
one measure of the (linguistic) feasibility of cooperative error
processing: the effectiveness of shallow processing over errors revealed
by the keystroke-record data.  There does not appear
to be an English source of this kind, so it is planned to compile one.
</P>
<P>
For comparison, a variety of other data has been collected.  Preliminary tests
used generated errors, from a program that produces random Damerau slips
according
to an observed distribution (Pollock, 1983), using confusion matrices where
appropriate (Kernighan, 1990).  Assembled data includes the
Birkbeck corpus (Mitton, 1986) and multifarious misspelling lists (without
context).  Suggestions have been made to look for low frequency words in
corpora and news/mail archives, and to the Longmans learner corpus
(not native speakers).
</P>
</DIV>
<DIV ID="4" DEPTH="1" R-NO="4"><HEADER>  Acknowledgements </HEADER>
<P>
 Thanks to all who offered advice on finding data, and to Doug McIlroy,
Sue Blackwell and Neil Rowe for sending me their misspelling lists.
</P>
<P>
This work is supported by a British Telecom Scholarship, administered
by the Cambridge Commonwealth Trust in conjunction with the Foreign and
Commonwealth Office.
</P>
<DIV ID="4.1" DEPTH="2" R-NO="1"><HEADER>Bibliography </HEADER>
<P>
  Hiyan Alshawi. 1992.
The Core Language Engine. Cambridge, Massachusetts: The MIT Press.
</P>
<P>
  Fred J. Damerau. 1964.
``A Technique for Computer Detection and Correction of Spelling Errors",
</P>
<P>
  Roger Garside, Geoffrey Leech and Geoffrey Sampson, eds.
1987.
The Computational Analysis of English.  Longman.
Commun. ACM, 7(3):171-176.
</P>
<P>
  Claire Grover, John Carroll and Ted Briscoe. 1993.
``The Alvey Natural Language Tools Grammar (4th Release)",
Tech. Rep. 284, Computer Lab, University of Cambridge.
</P>
<P>
  Mark D. Kernighan, Kenneth W. Church and William A. Gale.
1990.
``A Spelling Correction Program Based on a Noisy Channel Model",
Proc. Coling-90, pp 205-210.
</P>
<P>
  Roger Mitton, ed. 1986.
A Collection of Computer-Readable Corpora of English Spelling Errors (ver. 2).
Birkbeck College, University of London.
</P>
<P>
  Joseph J. Pollock and Antonio Zamora. 1983.
``Collection and Characterization of Spelling Errors in Scientific and
Scholarly Text",
J. Am. Soc. Inf. Sci., 34(1):51-58.
</P>
<P>
  Stephen G. Pulman and Mark R. Hepple. 1993.
``A feature-based formalism for two-level phonology: a description and
implementation",
Computer Speech and Language, 7(4):333-358.
</P>
<P>
  Edward M. Riseman and Allen R. Hanson. 1974.
``A Contextual Postprocessing System for Error Correction Using Binary n-Grams",
IEEE Trans. Comput., C-23(5):480-493.
</P>
<DIV ID="4.1.1" DEPTH="3" R-NO="1"><HEADER>Footnotes</HEADER>
<P>
   In particular, there are
  many HCI issues associated with such a system, which are beyond the
  scope of this paper.
</P>
</DIV>
</DIV>
</DIV>
</BODY>
</MINIMAL-DOC>
